### ISSUE TITLE
Not work after Home Assistant 2021.6 update

### ISSUE THREAD

**Issue by samuelepuccinelli** [abacao/hass_wibeee#4]
I use home assistant with raspberry pi 4 and hass_wibeee installed via HACS.
After updating HA to core-2021.6.2 version, hass_wibeee does not work.
I went back to the core-2021.5.5 version and this works with it.

**Comment by samuelepuccinelli** [comment]
I use home assistant with raspberry pi 4 and hass_wibeee installed via HACS.
After updating to core version 2021.6, hass_wibeee does not work.

**Comment by NGRaposo** [comment]
me too, what is the solution?

**Comment by samuelepuccinelli** [comment]
I just solved the problem by following the suggestion of this link https://github.com/juanjoSanz/hass_wibeee/pull/13/files

I added the "version" line to the manifest.json file
